---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cowsay-server
spec:
  selector:
    matchLabels:
      name: cowsay-server
  replicas: 1
  template:
    metadata:
      labels:
        name: cowsay-server
    spec:
      containers:
      - name: cowsay-server
        image: bgulla/mooit
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: cowsay-server
  labels:
    name: cowsay-server
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    name: cowsay-server
